controller:
  image:
    registry: docker.io
    repository: jenkins/jenkins
    tag: "2.426.1-lts"
  
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1000m"
      memory: "2Gi"

  serviceType: LoadBalancer
  servicePort: 8080
  
  # WARNING: do NOT commit real credentials. Use a secret (Kubernetes Secret, AWS Secrets Manager,
  # or a CI secret) and reference it here or via the helmProvider / extraEnv.
  # Example: set password to "{{ .Values.adminPassword | default (lookup secret ...) }}" or
  # leave placeholder and inject using `kubectl create secret generic jenkins-admin --from-literal=adminPassword=...`.
  admin:
    username: admin
    password: "<REPLACE_WITH_SECRET_OR_REFERENCE>"


  installPlugins: []

persistence:
  enabled: true
  storageClass: "gp2"
  size: "10Gi"

rbac:
  create: true

serviceAccount:
  create: true